#pragma once

// RegistryOps.h
#ifndef _REGISTRY_OPS_H_
#define _REGISTRY_OPS_H_

#define IOCTL_REG_CREATE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_REG_APPEND CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_REG_READ   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_REG_CLEAR  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

NTSTATUS RegCreateComplicatedPot();
NTSTATUS RegAppendToComplicatedPot(WCHAR* data, size_t length);
NTSTATUS RegReadComplicatedPot(WCHAR* outBuffer, size_t bufferSize);
NTSTATUS RegClearComplicatedPot();

#endif // _REGISTRY_OPS_H_
